### ISSUE TITLE
Using with puppeteer

### ISSUE THREAD

**Issue by gsasouza** [1stdibs/relay-mock-network-layer#10]
How can I use it with pupeteer? Since puppeteer access a url with page, how can I change my enviroment dynamicly?

**Comment by robrichard** [comment]
I think this is outside the scope of this library. Puppeteer has an api to mock network responses: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#requestrespondresponse

Alternatively you can write a relay network layer that dynamically decides to use a real network or this library.
